name: datascience
channels:
- defaults
- conda-forge
dependencies:
- beautifulsoup4
- ipython
- ipywidgets
- jupyter
- matplotlib
- notebook
- numpy
- openpyxl
- pandas
- pip
- psycopg2
- python
- pyyaml
- requests
- seaborn
- scipy
- scikit-learn
- spacy
- statsmodels
- xgboost
- wordcloud